name: 🤖CI run Test Suite Execution🧪
run-name: ${{github.actor}}👨🏻‍🔬 ran SanityTest in ${{github.ref_name}}

on: # This Run is a template. The correct "Run On" should be: Any except QA and Main
    push:
        branches: ['test/GX-346/Insertar-Informacion-Comprador']

jobs:
    SanityTest:
        name: Sanity Test
        runs-on: ubuntu-latest

        steps:
            - name: 💻Checkout
              uses: actions/checkout@v3

            - name: 💿Set up JAVA 20 with Maven
              uses: actions/setup-java@v3
              with:
                  java-version: '20'
                  distribution: 'temurin'
                  cache: maven

            - name: 🧬Install All Dependencies with Maven
              run: mvn -B package --file pom.xml

            - name: 🧪Run Selenium tests
              run: mvn clean verify -Dit.test=BuyerPaymentYMTest -Dheadless=true

            - name: ✅Import Test Results to Xray
              if: always()
              uses: mikepenz/xray-action@v2
              with: #todo: OPCIONES PARA IMPORTAR LOS RESULTADOS DE PRUEBA A JIRA XRAY:
                  username: ${{secrets.XRAY_CLIENT_ID}}
                  password: ${{secrets.XRAY_CLIENT_SECRET}}
                  testFormat: 'junit' #OPCIONES PARA CAMBIAR: 'junit' (para xml) o 'cucumber' (para json)
                  testPaths: 'target/failsafe-reports/TEST-*.xml'
                  testExecKey: 'GX3-350' #? EDITAR AQUÍ EL TEST EXECUTION A IMPORTAR LAS PRUEBAS.
                  projectKey: 'GX3' #? EDITAR EN CASO DE TRABAJAR CON OTRO PROYECTO.

            - name: 🔔Slack Notification of Done
              if: always()
              uses: rtCamp/action-slack-notify@v2.2.0
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  SLACK_USERNAME: Ari✨
                  SLACK_MESSAGE: ':test_tube: SELENIUM-JAVA (SwagLabs): Test Execution is Done and updated in Jira :rocket:'
                  SLACK_COLOR: ${{ job.status }}
                  SLACK_ICON: https://i.imgur.com/q9kvQCp_d.webp?maxwidth=760&fidelity=grand
